<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>Alessandro Wilner</Authors>
    <Description>A simple wrapper around the Questrade API</Description>
    <PackageTags>Questrade Api</PackageTags>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryUrl>https://github.com/awilner/QuestradeApiWrapper</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <Company />
    <Version>0.5.1</Version>
    <PackageReleaseNotes>Include source link</PackageReleaseNotes>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageProjectUrl>https://github.com/awilner/QuestradeApiWrapper</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(SolutionDir)README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>
</Project>
